import type { NextPage } from "next";

import Header from "../shared/components/Client/Header";


const Home: NextPage = () => {
  // const handleUpload = (e: any) => {
  //   const file = e.target.files[0];
  //   const formData = new FormData();
  //   formData.append("file", file);

  //   axios({
  //     method: "POST",
  //     url: "/api/uploads",
  //     headers: {
  //       "Content-Type": "multi-part",
  //     },
  //     data: formData,
  //   });
  // };

  return (
    <div className="overflow-x-hidden">
      <head>
        <title>Foody | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <header className="bg-#F3F4F6 m-0 sm:m-8 flex-col rounded-md">
        <Header />
      </header>
      <main></main>
      
    </div>
  );
};

export default Home;
